apiVersion: apps/v1
kind: Deployment
metadata:
  name: quick-order-deployment
  labels:
    app: quick-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quick-order
  template:
    metadata:
      labels:
        app: quick-order
    spec:
      containers:
      - name: quickordercontainer
        image: 28101976/quickorder-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
